# frozen_string_literal: true

source 'https://rubygems.org'

# needed for Jekyll
gem 'jekyll', '~> 4.4.1'
gem 'logger', '~> 1.7'
gem 'ostruct', '~> 0.6.3'

# needed for Rake tasks
gem 'rake', '~> 13.3.1'
gem 'csv', '~> 3.3.5'
gem 'fileutils', '~> 1.8'
gem 'mini_magick', '~> 5.3.1'

gem 'image_optim', '~> 0.31.4', platforms: :ruby
gem 'image_optim_pack', '~> 0.12.2', platforms: :ruby
